---
compilation:
  cloud_properties: {}
  network: vault
  reuse_compilation_vms: true
  workers: 1
director_uuid: eccd33fa-a9bd-4014-99be-d5ac55db0788
disk_pools: []
jobs:
- instances: 3
  name: vault
  networks:
  - name: vault
    static_ips:
    - 10.244.8.2
    - 10.244.8.3
    - 10.244.8.4
  persistent_disk: 4096
  properties:
    consul:
      join_hosts:
      - 10.244.8.2
      - 10.244.8.3
      - 10.244.8.4
    vault:
      backend:
        use_consul: true
  resource_pool: small
  templates:
  - name: vault
    release: vault
  - name: consul
    release: consul
name: vsphere-alpha-vault
networks:
- name: vault
  subnets:
  - gateway: 10.244.8.1
    range: 10.244.8.0/24
    static:
    - 10.244.8.2 - 10.244.8.60
  type: manual
properties:
  vault:
    ha:
      domain: 10.244.8.2.sslip.io
releases:
- name: consul
  sha1: 9a0591c6b4d88d7d756ea933e14ddf112d05f334
  url: https://bosh.io/d/github.com/cloudfoundry-community/consul-boshrelease?v=20
  version: '20'
- name: vault
  version: 0.4.1
resource_pools:
- cloud_properties: {}
  name: small
  network: vault
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: '3262.2'
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 1
  serial: true
  update_watch_time: 1000-60000
